#include "WxEmitter.h"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace wxConvert {

namespace {
std::string sanitizeIdent(std::string s)
{
    // Turn RC ids (IDD_FOO) into a safe C++ identifier suffix.
    for (auto& ch : s) {
        if (!std::isalnum(static_cast<unsigned char>(ch))) ch = '_';
    }
    if (!s.empty() && std::isdigit(static_cast<unsigned char>(s[0]))) s = "_" + s;
    return s;
}

std::string cppStringLiteral(const std::string& s)
{
    std::ostringstream oss;
    oss << "\"";
    for (char c : s) {
        switch (c) {
            case '\\': oss << "\\\\"; break;
            case '"': oss << "\\\""; break;
            case '\n': oss << "\\n"; break;
            case '\r': oss << "\\r"; break;
            case '\t': oss << "\\t"; break;
            default: oss << c; break;
        }
    }
    oss << "\"";
    return oss.str();
}

bool containsToken(const std::string& haystack, const char* needle)
{
    return haystack.find(needle) != std::string::npos;
}

std::string wxTextCtrlStyleFromRc(const std::string& rcStyle)
{
    std::string out;
    if (containsToken(rcStyle, "ES_READONLY")) out += " | wxTE_READONLY";
    if (containsToken(rcStyle, "ES_MULTILINE")) out += " | wxTE_MULTILINE";
    // ES_AUTOHSCROLL is default-ish; skip.
    if (out.empty()) return "0";
    return out.substr(3); // drop leading " | "
}

std::string wxListCtrlStyleFromRc(const std::string& rcStyle)
{
    // Minimal mapping for the sample: LVS_REPORT -> wxLC_REPORT
    std::string out = "wxLC_REPORT";
    if (containsToken(rcStyle, "WS_BORDER")) out += " | wxBORDER_SIMPLE";
    return out;
}
} // namespace

WxEmitResult WxEmitter::emit(const RcDialog& dialog) const
{
    std::ostringstream h;
    std::ostringstream c;
    const std::string cls = "Rc" + sanitizeIdent(dialog.name);

    h << "#pragma once\n\n";
    h << "#include <wx/wx.h>\n";
    h << "#include <wx/listctrl.h>\n";
    h << "#include <wx/notebook.h>\n\n";

    h << "// Generated by rc2WxWidgets (one-time conversion)\n\n";

    c << "#include \"" << cls << ".h\"\n\n";
    c << "// Generated by rc2WxWidgets (one-time conversion)\n\n";

    WxEmitResult out;
    out.className = cls;

    if (dialog.isChild()) {
        h << "class " << cls << " : public wxPanel\n{\npublic:\n";
        h << "    explicit " << cls << "(wxWindow* parent);\n";
        h << "};\n\n";

        c << cls << "::" << cls << "(wxWindow* parent)\n";
        c << "    : wxPanel(parent, wxID_ANY)\n{\n";
    }
    else {
        h << "class " << cls << " : public wxDialog\n{\npublic:\n";
        h << "    explicit " << cls << "(wxWindow* parent);\n";
        h << "};\n\n";

        c << cls << "::" << cls << "(wxWindow* parent)\n";
        c << "    : wxDialog(parent, wxID_ANY, " << cppStringLiteral(dialog.caption.empty() ? dialog.name : dialog.caption)
            << ", wxDefaultPosition, wxDefaultSize,\n";
        c << "        wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER)\n{\n";
    }

    if (dialog.fontPointSize > 0 && !dialog.fontFace.empty()) {
        c << "    SetFont(wxFontInfo(" << dialog.fontPointSize << ").FaceName("
            << cppStringLiteral(dialog.fontFace) << "));\n";
    }

    // Size in dialog units; let wx convert to pixels.
    c << "    SetClientSize(ConvertDialogToPixels(wxSize(" << dialog.rectDU.w << ", " << dialog.rectDU.h << ")));\n\n";

    c << "    auto DUPoint = [this](int x, int y) { return ConvertDialogToPixels(wxPoint(x, y)); };\n";
    c << "    auto DUSize  = [this](int w, int h) { return ConvertDialogToPixels(wxSize(w, h)); };\n\n";

    for (const auto& ctl : dialog.controls) {
        const auto& r = ctl.rectDU;
        const std::string idExpr = "wxID_ANY"; // safer default; user can map later

        switch (ctl.kind) {
            case RcControlKind::LText:
            case RcControlKind::CText:
            case RcControlKind::RText:
                c << "    new wxStaticText(this, " << idExpr << ", " << cppStringLiteral(ctl.text)
                    << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                break;
            case RcControlKind::GroupBox:
                c << "    new wxStaticBox(this, " << idExpr << ", " << cppStringLiteral(ctl.text)
                    << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                break;
            case RcControlKind::EditText:
                c << "    new wxTextCtrl(this, " << idExpr << ", wxEmptyString"
                    << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << ")"
                    << ", " << wxTextCtrlStyleFromRc(ctl.style) << ");\n";
                break;
            case RcControlKind::ComboBox:
                c << "    new wxComboBox(this, " << idExpr << ", wxEmptyString"
                    << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                break;
            case RcControlKind::PushButton:
            case RcControlKind::DefPushButton:
                c << "    {\n";
                c << "        auto* btn = new wxButton(this, " << idExpr << ", " << cppStringLiteral(ctl.text)
                    << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                if (ctl.kind == RcControlKind::DefPushButton) c << "        btn->SetDefault();\n";
                c << "    }\n";
                break;
            case RcControlKind::Control:
                if (ctl.winClass == "SysListView32") {
                    c << "    new wxListCtrl(this, " << idExpr
                        << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << ")"
                        << ", " << wxListCtrlStyleFromRc(ctl.style) << ");\n";
                }
                else if (ctl.winClass == "SysTabControl32") {
                    c << "    new wxNotebook(this, " << idExpr
                        << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                }
                else if (ctl.winClass == "Button" && containsToken(ctl.style, "BS_AUTORADIOBUTTON")) {
                    c << "    new wxRadioButton(this, " << idExpr << ", " << cppStringLiteral(ctl.text)
                        << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                }
                else {
                    c << "    // TODO: CONTROL class " << cppStringLiteral(ctl.winClass) << "\n";
                    c << "    new wxWindow(this, " << idExpr
                        << ", DUPoint(" << r.x << ", " << r.y << "), DUSize(" << r.w << ", " << r.h << "));\n";
                }
                break;
            case RcControlKind::Icon:
                c << "    // TODO: ICON " << cppStringLiteral(ctl.id) << " at " << r.x << "," << r.y << "\n";
                break;
            default:
                break;
        }
    }

    c << "}\n\n";

    out.header = h.str();
    out.source = c.str();
    return out;
}

} // namespace wxConvert